USE sakila
# List the number of films per category.
SELECT category.name, COUNT(film_category.film_id) as nuevo_coluna
FROM category
JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.name;
# Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM store
JOIN address ON store.address_id = address.address_id
JOIN city ON address.city_id = city.city_id
JOIN country ON country.country_id = city.country_id
GROUP BY store_id;
# calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount)
FROM store
JOIN customer ON customer.store_id = store.store_id
JOIN payment ON customer.customer_id = payment.customer_id
GROUP BY store.store_id;

# Determine the average running time of films for each category.
SELECT category.name, AVG(film.length)
FROM category
JOIN film_category ON category.category_id = film_category.category_id
JOIN film ON film_category.film_id = film.film_id
GROUP BY category.category_id;